# prettier-ignore
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    inputs:
      destination:
        description: "Define destination base path"
        required: true
        default: "manual_run"
name: Site deploy preview

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            pull-requests: write
            contents: read
        steps:
            - name: update PR
              if: ${{ github.event_name == 'pull_request' }}
              uses: thollander/actions-comment-pull-request@v2
              with:
                 message: |
                     Started attempt to build a new deploy preview for PR ${{ github.event.pull_request.number }}.
                 comment_tag: pr_published
            - name: Checkout your repository using git
              uses: actions/checkout@v3
              with:
                 ref:
                     ${{ github.event_name == 'pull_request' &&
                     github.event.pull_request.head.sha || github.ref }}
            - name: Install, build, and upload your site output
              uses: withastro/action@v3
            - run: ls -la

    deploy-website:
        runs-on: ubuntu-latest
        permissions:
          pull-requests: write
          contents: read
        needs: build
        steps:
            - uses: actions/download-artifact@v4
              with:
                  name: github-pages
            - run: ls -la
            - run: mkdir dist/
            - run: tar -xvf artifact.tar -C dist/
            - run: ls -la
            - name: Deploy to Server
              uses: easingthemes/ssh-deploy@main
              with:
                  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
                  ARGS: "-rlgoDzvc -i --delete"
                  SOURCE: "dist/"
                  REMOTE_HOST: ${{ vars.REMOTE_HOST }}
                  REMOTE_USER: ${{ vars.REMOTE_USER }}
                  TARGET: ${{ vars.REMOTE_TARGET }}${{ github.event_name == 'pull_request' && github.event.pull_request.number ||  github.event_name == 'push' && 'main' || github.event.inputs.destination}}
            - name: update PR
              if: ${{ github.event_name == 'pull_request' }}
              uses: thollander/actions-comment-pull-request@v2
              with:
                  message: |
                      Created a new deploy preview for PR ${{ github.event.pull_request.number }}. [See preview](http://community-at-preview.fujocoded.dev/${{ github.event.pull_request.number }}/).
                  comment_tag: pr_published
