on:
  push:
    branches:
      - main # work off main branch
  pull_request_target: # this workflow triggers either when there's a push to main OR when a PR is opened/updated
    types: [opened, synchronize, reopened]
  workflow_dispatch: # it also can be triggered manually, and in that case the destination will be required and called "manual_run"
    inputs:
      destination:
        description: "Define destination base path"
        required: true
        default: "manual_run"

jobs:
  call-workflow:
    uses: FujoWebDev/.github/.github/workflows/deploy-preview-static.yaml@main
